# Generated by Django 5.0.7 on 2024-08-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_nigga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nigga',
        ),
    ]
