# Generated by Django 5.0.7 on 2024-08-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidplan',
            name='special',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
