# Generated by Django 5.0.7 on 2024-08-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_prepaidplan_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaidplan',
            name='name',
        ),
        migrations.AlterField(
            model_name='prepaidplan',
            name='data',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prepaidplan',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prepaidplan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prepaidplan',
            name='validity',
            field=models.IntegerField(),
        ),
    ]
